In [115]:
#importing numpy library
import numpy as np 

In [78]:
# Create a numpy array of first five even numbers

In [116]:
arr1 = np.arange(0,10,2)

In [117]:
arr1

array([0, 2, 4, 6, 8])

In [118]:
arr2 = np.array([0,2,4,6,8])

In [119]:
arr2

array([0, 2, 4, 6, 8])

 Write a Python program to create a NumPy array based on the following list:
 
list = [2, 5, 8, 6, 4, 12, 16, 15]

In [83]:
list1= [2, 5, 8, 6, 4, 12, 16, 15]

In [84]:
arr3 = np.array(list1)

In [85]:
arr3

array([ 2,  5,  8,  6,  4, 12, 16, 15])

In [86]:
arr3.ndim

1

In [87]:
np.linspace(17,31,50)

array([17.        , 17.28571429, 17.57142857, 17.85714286, 18.14285714,
       18.42857143, 18.71428571, 19.        , 19.28571429, 19.57142857,
       19.85714286, 20.14285714, 20.42857143, 20.71428571, 21.        ,
       21.28571429, 21.57142857, 21.85714286, 22.14285714, 22.42857143,
       22.71428571, 23.        , 23.28571429, 23.57142857, 23.85714286,
       24.14285714, 24.42857143, 24.71428571, 25.        , 25.28571429,
       25.57142857, 25.85714286, 26.14285714, 26.42857143, 26.71428571,
       27.        , 27.28571429, 27.57142857, 27.85714286, 28.14285714,
       28.42857143, 28.71428571, 29.        , 29.28571429, 29.57142857,
       29.85714286, 30.14285714, 30.42857143, 30.71428571, 31.        ])

In [88]:
arr4 = np.arange(16)

In [121]:
arr4.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
L = [10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41]

In [123]:
arr5 = np.array(L)

In [124]:
arr5

array([10,  2,  7,  8,  3, 22, 54, 12, 13, 46, 23, 25, 41])

In [125]:
arr5 = np.sort(arr5)

In [126]:
arr5

array([ 2,  3,  7,  8, 10, 12, 13, 22, 23, 25, 41, 46, 54])

In [127]:
arr5 = np.delete(arr5,4)

In [128]:
arr5

array([ 2,  3,  7,  8, 12, 13, 22, 23, 25, 41, 46, 54])

In [129]:
L.append(53)

In [130]:
L

[10, 2, 7, 8, 3, 22, 54, 12, 13, 46, 23, 25, 41, 53]

In [131]:
arr6 = np.reshape(L,(2,7))

In [132]:
arr6

array([[10,  2,  7,  8,  3, 22, 54],
       [12, 13, 46, 23, 25, 41, 53]])

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.array([0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr7 = np.arange(15)

In [102]:
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
arr8=np.reshape(arr7,(3,5))

In [104]:
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [105]:
arr8[2][3]

13

In [106]:
arr8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [107]:
arr8[1:3,2:5]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [108]:
arr8[-2:,-3:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [138]:
arr = np.arange(25)

In [139]:
arr = np.reshape(arr,(5,5))

In [140]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [141]:
arr.ndim

2

In [137]:
arr[0:2,3:5]

array([[3, 4],
       [8, 9]])

In [142]:
arr[1:5:2,0:5:2]

array([[ 5,  7,  9],
       [15, 17, 19]])